swagger: "2.0"
info:
  description: "This is the API documentation for the Suppliers Resource for the NYU DevOps Class, Spring 2020. 
  #You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."#
  version: "1.0.0"
  title: "Supplier Resource NYU DevOps Spring 2020"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "lf1832@stern.nyu.edu"
  license:
    name: "Apache 2.0"
    url: "localhost:5000"
host: "localhost:5000"
basePath: "/api"
tags:
- name: "Suppliers"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /suppliers:
    get:
      tags:
      - "Retrieving Suppliers and Supplier Details"
      summary: "Get a list of suppliers"
      description: "This endpoint uses a get request to retrieve all suppliers"
      operationId: "listSuppliers"
      produces:
      - "application/json"
      responses:
        "405":
          description: "Invalid input"
    post:
      tags:
      - "Creating a Supplier"
      summary: "Create a Supplier"
      description: ""
      operationId: "createSupplier"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "New supppliers to be added to Resource"
        required: true
        schema:
          $ref: "#/definitions/Supplier"
      responses:
        "400":
          description: "Invalid details supplied"
        "404":
          description: "Supplier not added"
        "405":
          description: "Validation exception"

  /suppliers/{supplier_id}:
    get:
      tags:
      - "Retrieving Suppliers and Supplier Details"
      summary: "Find supplier by ID"
      description: "Returns a single supplier"
      operationId: "getSupplierById"
      produces:
      - "application/json"
      parameters:
      - name: "supplier_id"
        in: "path"
        description: "ID of supplier to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Supplier"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Supplier not found"
    delete:
      tags:
      - "Changing/Deleting Supplier Information"
      summary: "Delete A Supplier"
      description: ""        
      operationId: "deleteSupplier"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "supplier_id"
        in: "path"
        description: "ID of supplier to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Supplier not found"
        "405":
          description: "Validation exception"  
  /suppliers/{supplier_id}/preferred:
    put:
      tags:
      - "Changing/Deleting Supplier Information"
      summary: "Mark a Supplier as Preferred"
      description: ""
      operationId: "markSupplier"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "supplier_id"
        in: "path"
        description: "ID of supplier to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Supplier not found"
        "405":
          description: "Validation exception"
definitions:
  Supplier:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      category:
        type: "string"
      preferred:
        type: "boolean"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"